### ISSUE TITLE
Segmentation from user-defined point broken

### ISSUE THREAD

**Issue by DanielThedie** [jeanollion/bacmman#10]
Hello,

The segmentation of missed cells by using (c + ctrl-c) doesn't seem to work anymore. When pressing ctrl-c it throws an error:
![image](https://user-images.githubusercontent.com/62017239/193242165-4d8d6f73-0006-4cc6-aa89-e4e28aaa6251.png)

Steps to reproduce:
- Open kymograph for Unet-segmented cells
- Delete a cell
- Press c
- Click inside the previously deleted cell (places a marker)
- Press ctrl-c (error occurs)

**Comment by jeanollion** [comment]
Hello Daniel, 
The problem is solved in the latest version. Thanks for pointing that out. 
Best, 
Jean
