### ISSUE TITLE
ilastik4ij API has changed in 2.0

### ISSUE THREAD

**Issue by k-dominik** [jeanollion/bacmman#12]
Dear @jeannollion,

I've noticed you're depending on the [ilastik4ij plugin](https://github.com/ilastik/ilastik4ij). The java API has changed with the release of 2.0, which means that bacmman-ilastik will not work with the current version, unfortunately. I'm sorry for the inconvenience this causes you. There are some [examples/demos for the new API in our repo](https://github.com/ilastik/ilastik4ij/tree/main/src/test/java/org/ilastik/ilastik4ij/demo).

Sorry again.
Cheers
Dominik

**Comment by jeanollion** [comment]
Dear @k-dominik 
Thanks for letting me know. 
Best Regards, 
Jean Ollion
