### ISSUE TITLE
Configuration emptied when importing images

### ISSUE THREAD

**Issue by MoMa941** [jeanollion/bacmman#13]
Dear @jeannollion,

I am currently trying to work with DistNet and for this I am following the wiki page. I import the dataset/configuration from the online library, after which the configuration tab becomes red. When checking the configuration tab, there is no setting showing red and the settings look good for the dataset. When leaving the configuration tab however it becomes red again. After this I download the sample dataset 'mother machine phase contrast' and I import them. At this point I get a warning, no images get imported and the configuration tab lacks any settings. The images do not get imported because the import method now shows 'no selection'.

I did not run into this problem before, but now it also does this when I try to run my old data on my own configurations. 

What could be a reason for this happening? 

kind regards,

Tom

**Comment by jeanollion** [comment]
Dear Tom, 
Thanks for pointing that out. Bug is resolved, you just need to update. 
Best Regards, 
Jean
