### ISSUE TITLE
Headless Mode

### ISSUE THREAD

**Issue by joagutierrez** [jeanollion/bacmman#4]
Hi!

Thanks a lot for making and maintaining this package! I've just started working with the mother machine and this is of tremendous help.

I'm trying to install from the command line in order to run in headless mode in the future. I have installed git (version 2.18.0.windows.1), maven (apache-maven-3.6.3) and JDK (jdk-11.0.6), but when I run the command

`mvn clean dependency:copy-dependencies package`

there is one test that is not successful. I get the following message: 

> 
> Results :
> 
> Failed tests:   deleteTestDBMap(bacmman.image.DeleteFromDAOTest): DAO type: DBMapMasterDAO; number of measurements after by structureIdx expected:<1> but was:<2>
> 
> Tests run: 39, Failures: 1, Errors: 0, Skipped: 0
> 
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for BACMMAN 3.0.0:
> [INFO]
> [INFO] BACMMAN ............................................ SUCCESS [  1.453 s]
> [INFO] bacmman-core ....................................... FAILURE [01:34 min]
> [INFO] bacmman-github ..................................... SKIPPED
> [INFO] bacmman-gui ........................................ SKIPPED
> [INFO] bacmman-modules-mother-machine ..................... SKIPPED
> [INFO] bacmman-dl ......................................... SKIPPED
> [INFO] bacmman-tf ......................................... SKIPPED
> [INFO] bacmman-ij1_ ....................................... SKIPPED
> [INFO] bacmman-headless ................................... SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  01:37 min
> [INFO] Finished at: 2020-03-22T21:29:32+01:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project bacmman-core: There are test failures.
> [ERROR]
> [ERROR] Please refer to F:\Joaquin\Microscopy\Bacmman\bacmman\bacmman-core\target\surefire-reports for the individual test results.
> [ERROR] -> [Help 1]
> [ERROR]
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR]
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR]
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :bacmman-core

The result of the individual test that didn't pass is the following

> -------------------------------------------------------------------------------
> Test set: bacmman.image.DeleteFromDAOTest
> -------------------------------------------------------------------------------
> Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 38.812 sec <<< FAILURE!
> deleteTestDBMap(bacmman.image.DeleteFromDAOTest)  Time elapsed: 17.672 sec  <<< FAILURE!
> java.lang.AssertionError: DAO type: DBMapMasterDAO; number of measurements after by structureIdx expected:<1> but was:<2>
> 	at org.junit.Assert.fail(Assert.java:93)
> 	at org.junit.Assert.failNotEquals(Assert.java:647)
> 	at org.junit.Assert.assertEquals(Assert.java:128)
> 	at org.junit.Assert.assertEquals(Assert.java:472)
> 	at bacmman.image.DeleteFromDAOTest.deleteTest(DeleteFromDAOTest.java:203)
> 	at bacmman.image.DeleteFromDAOTest.deleteTestDBMap(DeleteFromDAOTest.java:109)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
> 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
> 	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
> 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
> 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

Unfortunately, I don't know how to correct the error to proceed. Any help would be much appreciated!!

Thanks,

Joaquin

**Comment by sabilab** [comment]
Hi Joaquin, 
Thanks for your detailed message. 
It seems to be a windows-related problem as the test do not fail in my linux machines. Unfortunately I don't have access to a windows machine right now due to the actual situation! 
For now you can run the maven command without the tests (-DskipTests=true). 
I have an idea of what the problem might be so i'll try to make a patch in the next few days so you can run the tests on your windows machine. 
best, 
Jean

PS: FYI, I just wrote an [article](https://jeanollion.github.io/project/2020/03/19/distnet.html) on a new method for detection of bacteria in phase-contrast images, you might be interested.

**Comment by jeanollion** [comment]
Hi Joaquin, 
I did a few modifications, unfortunately I can't test on a windows machine. 
you can try by git-pulling the master and running the command with the tests this time
best, 
Jean

**Comment by joagutierrez** [comment]
Hi Jean,

Thank you for your quick answer and for your help!

I have pulled the newest version from master and re-run the 

`mvn clean dependency:copy-dependencies package`

command.

However, I get exactly the same error as before.

Here's the detailed error log:


> -------------------------------------------------------------------------------
> 
> Test set: bacmman.image.DeleteFromDAOTest
> -------------------------------------------------------------------------------
> Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 38.158 sec <<< FAILURE!
> deleteTestDBMap(bacmman.image.DeleteFromDAOTest)  Time elapsed: 18.232 sec  <<< FAILURE!
> java.lang.AssertionError: DAO type: DBMapMasterDAO; number of measurements after by structureIdx expected:<1> but was:<2>
> 	at org.junit.Assert.fail(Assert.java:93)
> 	at org.junit.Assert.failNotEquals(Assert.java:647)
> 	at org.junit.Assert.assertEquals(Assert.java:128)
> 	at org.junit.Assert.assertEquals(Assert.java:472)
> 	at bacmman.image.DeleteFromDAOTest.deleteTest(DeleteFromDAOTest.java:205)
> 	at bacmman.image.DeleteFromDAOTest.deleteTestDBMap(DeleteFromDAOTest.java:109)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
> 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
> 	at org.junit.rules.RunRules.evaluate(RunRules.java:18)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
> 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
> 	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
> 	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
> 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
> 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
> 

I believe the only difference to before is in line:  

> at bacmman.image.DeleteFromDAOTest.deleteTest(DeleteFromDAOTest.java:205)

Thank you again for the help!

Best,

Joaquín

P.S. I'd be very interested in having a look at your paper! Unfortunately, the link you sent is broken. Is it this paper maybe? https://www.groundai.com/project/distnet-deep-tracking-by-displacement-regression-application-to-bacteria-growing-in-the-mother-machine/1
